### ISSUE TITLE
Adding awesome-helix to main awesome repo

### ISSUE THREAD

**Issue by pawelgrzybek** [rajasegar/awesome-helix#5]
Would you mind if I added a pull request to the main awesome repository that includes awesome-helix in the editors section? Today, I wanted to create an `awesome-helix` repository myself after I noticed that there isn't one on the main page. Then I came across your repository. Good job!

https://github.com/sindresorhus/awesome#editors

**Comment by rajasegar** [comment]
@pawelgrzybek I am perfectly fine with that

**Comment by pawelgrzybek** [comment]
NIce, I will submit that shortly.
